# Generated by Django 4.0.6 on 2022-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmpassword',
            field=models.CharField(default='0123', max_length=30),
        ),
    ]
