# Generated by Django 4.0.6 on 2022-07-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_myuser_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmpassword',
        ),
    ]
