# Generated by Django 4.0.5 on 2022-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='specialization',
            field=models.CharField(choices=[('poultry', 'poultry'), ('equine', 'equine'), ('ruminant', 'ruminant'), ('fishes and aquatics', 'fishes and aquatics'), ('obstetrics and gynecology', 'obstetrics and gynecology')], max_length=100),
        ),
    ]
