# Generated by Django 4.0.5 on 2022-07-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_alter_vet_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('website_link', models.URLField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('work_hours_start', models.IntegerField()),
                ('work_hours_start_period', models.CharField(max_length=2)),
                ('work_hours_end', models.IntegerField()),
                ('work_hours_end_period', models.CharField(max_length=2)),
            ],
        ),
    ]
