# Generated by Django 4.0.5 on 2022-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_alter_locations_work_hours_end_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='locations',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
