# Generated by Django 4.0.5 on 2022-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_alter_locations_mobile_alter_locations_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='active_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='b_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='face_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
