# Generated by Django 4.0.5 on 2022-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_alter_vet_active_link_alter_vet_b_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('date', models.DateField(default='19/07/2022 12:48:12')),
            ],
        ),
        migrations.AlterField(
            model_name='vet',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
