# Generated by Django 4.0.6 on 2022-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_messages_alter_vet_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateField(default='19/07/2022 16:37:33'),
        ),
    ]
