# Generated by Django 4.0.5 on 2022-07-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0011_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateField(default='20/07/2022 02:51:32'),
        ),
    ]
