# Generated by Django 4.0.5 on 2022-07-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default='20/07/2022 03:21:17'),
        ),
    ]
