# Generated by Django 4.0.5 on 2022-07-21 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0015_animal_alter_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='female_state',
            field=models.CharField(blank=True, choices=[('immature', 'immature'), ('mature&married', 'mature&married'), ('pregnant ', 'pregnant'), ('lactating', 'lactating')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('domestic', 'domestic'), ('wild', 'wild')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 7, 40, 9, 983119)),
        ),
    ]
