<<<<<<< HEAD
# Generated by Django 3.2.14 on 2022-07-21 08:31
=======
# Generated by Django 4.0.5 on 2022-07-21 10:51
>>>>>>> 6474e54db4d9b2ac29d43dcaaab25386621dfc76

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0016_animal_female_state_alter_animal_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 10, 31, 54, 71107)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 12, 51, 51, 745508)),
>>>>>>> 6474e54db4d9b2ac29d43dcaaab25386621dfc76
        ),
    ]
