# Generated by Django 4.0.5 on 2022-07-21 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0016_animal_female_state_alter_animal_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 12, 51, 51, 745508)),
        ),
    ]
