# Generated by Django 3.2.14 on 2022-07-21 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(
                2022, 7, 21, 15, 27, 17, 128500)),
        ),
    ]
